### PR TITLE
Delete some unnecessary files.

### PR DESCRIPTION
**Pull request by Nescio0**
`template_unit_champion_infantry_axeman.xml` is obsolete thanks to https://code.wildfiregames.com/rP23780
.DELETED is for disabling files from the *public* mod.
`player_defaults.json` is unnecessary.

### CODE REVIEW

**Comment by StanleySweet** [comment]
Notice the deleted files were just renamed so while the use of DELETED is dubious they contain actual backup code.

**Comment by Nescio0** [comment]
Everything is preserved in the .git history, there is no need to keep superfluous .DELETED files.

**Comment by StanleySweet** [comment]
Sure. but your comment above didn't suggest you actually looked into those files.

**Comment by StanleySweet** [comment]
Damn, closed i

**Comment by Nescio0** [comment]
What do you mean exactly?

**Comment by StanleySweet** [comment]
> .DELETED is for disabling files from the public mod.

Could just say, heh found those useless files, and deleted them. Since typically DELETED files don't have content (they need at least a char to be packaged though) you could have overlooked it :)

**Comment by Nescio0** [comment]
`gui/pregame/backgrounds.DELETED` is meaningful, it disables the backgrounds from the public mod, but that's not the case for `mainmenu_milleniumad.js.DELETED` and `session_millenniumad.js.DELETED`.

**Comment by StanleySweet** [comment]
Not my point, but doesn't matter anyway.

**Pull request merged**
